name: CI

on:
  push:
    branches: [ master ]
  # Allow manual workflow runs
  workflow_dispatch:

jobs:
  test1:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: test1
        run: make test1
  test2:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: test2
        run: make test2
